### PR TITLE
Revive Xenia-Project/1243

### PR DESCRIPTION
**Pull request by halotroop2288**
Basically, completely rewrites your whole thing on top of all the new changes.

I'm proposing this to you so you can still be in charge of the real PR.

Here are some screenshots (I have no idea why the build is called "master", it's built on branch "dashboard")
OOBE on 1888
Dash on 1888

OOBE on 6719
Dash on 6719

### CODE REVIEW

**Comment by emoose** [comment]
Heh I was just thinking of porting some stuff to the newest Xenia a couple hours ago, must have read my mind :o

I was mostly thinking about the stfs-writer stuff though, but looks like this is the stuff for getting dashboard running?

How were the changes merged anyway? The 950 commits kinda scares me, was that from rebasing onto master, or was it some other method?

**Comment by halotroop2288** [comment]
It was basically from rebasing. I just cloned master, added your changes in my commit, and pushed to a new branch for this PR.

**Comment by emoose** [comment]
Ah yeah I see, surprised those changes are still needed, those are really pretty low hanging fruit... hopefully Xenia will add them eventually (it's too bad RPCS3 beat it to getting the console dash running on master build, since we've had dash for months/years now, might have given us a lot of attention ;_;)

I think if I merged this into my dashboard branch it'd erase all the history there though, but I don't mind merging it into a new branch, `dashboard-new` or something, are you able to make a PR that creates a new branch here? Maybe I have to create it on this end first.

**Comment by halotroop2288** [comment]
You do have to create a new branch as a target. Yes.

**Comment by emoose** [comment]
Alright think I've made the `dashboard-new` branch, hopefully you can PR it to there, or maybe update this PR to update that.

**Pull request closed without merging**
